name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2'  # Match your Dockerfile

    - name: Run tests
      run: go test ./...  # Run tests before building

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated to latest version

    - name: Log in to Docker Hub
      uses: docker/login-action@v3  # Updated to latest version
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/go-api:$GITHUB_SHA -t ${{ secrets.DOCKER_USERNAME }}/go-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/go-api:$GITHUB_SHA
        docker push ${{ secrets.DOCKER_USERNAME }}/go-api:latest